### ISSUE TITLE
Modifying code to generate sepearete svg for each piece

### ISSUE THREAD

**Issue by ozanerturk** [lkesteloot/jigsaw#1]
Hi, This is great work you did here. Appreciated.
You mentionet in the article that you had modified the code to generate seperate svg files for each piece. can you detail how did you do it ?
Thanks.

**Comment by lkesteloot** [comment]
I've added a `--separate` flag to the script. The only difference between this puzzle and the original is that the original had rounded corners, and this would have been difficult to do the way that this one is done. (The rounded corners came from a single large rectangle for the entire outside edge.) Note that each piece is in its original place, but the script can be modified to output each piece at the origin instead.
